[package]
name = "dot_parse"
version = "0.2.0"
authors = ["lk-chen <lkchen_github@outlook.com>"]
edition = "2018"

[lib]
name = "libdot_parse"
path = "src/lib.rs"

[[bin]]
name = "dot_parse"
path = "src/bin.rs"

[dependencies]
dot = "0.1.4"
more-asserts = "0.2.1"
